source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '13.0'
use_frameworks!

target 'JHPopupManagerDemo' do  

pod 'JHPopupManager', :path => '../'
pod 'SnapKit', '~> 5.0.0'
pod 'JHGrandPopupView', '1.5.0'

end
